// Algorithm/Flowchart data-driven structure
// Each algorithm = list of decision/action steps. Some have branches.
// step: { id, kind:'check'|'action'|'goto'|'call', text, detail?, tone?, yesNextId?, noNextId?, nextId? }

export const algorithms = [
  {
    id: 'cpr',
    title: 'CPR ผู้ใหญ่ (Hands-only)',
    icon: 'Heart',
    color: '#DC2626',
    summary: 'การช่วยฟื้นคืนชีพแบบกดหน้าอกอย่างเดียว',
    steps: [
      { id: 's1', kind: 'check', text: 'ปลอดภัยพอที่จะเข้าใกล้หรือไม่?',
        yesNextId: 's2', noNextId: 'stop-danger' },
      { id: 'stop-danger', kind: 'action', tone: 'danger',
        text: 'ห้ามเข้าใกล้ — โทร 1669 จากที่ปลอดภัย', terminal: true },
      { id: 's2', kind: 'check', text: 'ตอบสนองเมื่อเรียก/เขย่าไหล่?',
        yesNextId: 'awake', noNextId: 's3' },
      { id: 'awake', kind: 'action', text: 'ดูแลให้อยู่ในท่าที่สบาย — สังเกตอาการ ถ้าผิดปกติโทร 1669', terminal: true },
      { id: 's3', kind: 'call', tone: 'danger', text: 'โทร 1669 และขอเครื่อง AED ทันที', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'หายใจปกติหรือไม่ (10 วินาที)?',
        yesNextId: 'recovery', noNextId: 's5' },
      { id: 'recovery', kind: 'action', text: 'จัดท่าตะแคง (Recovery position) เฝ้าสังเกต', terminal: true },
      { id: 's5', kind: 'action', text: 'กดหน้าอกกลางอก ลึก 5–6 ซม. 100–120 ครั้ง/นาที', nextId: 's6' },
      { id: 's6', kind: 'check', text: 'AED มาถึงแล้วหรือไม่?',
        yesNextId: 'aed', noNextId: 's5' },
      { id: 'aed', kind: 'goto', text: 'ไปที่ flowchart การใช้ AED', targetId: 'aed', terminal: true },
    ],
  },
  {
    id: 'aed',
    title: 'การใช้ AED',
    icon: 'Zap',
    color: '#2563EB',
    summary: 'เครื่องกระตุกหัวใจอัตโนมัติ',
    steps: [
      { id: 's1', kind: 'action', text: 'เปิดเครื่อง AED — ปฏิบัติตามเสียง', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'ติดแผ่นกับหน้าอกผู้ป่วยตามภาพ', nextId: 's3' },
      { id: 's3', kind: 'action', tone: 'warning', text: 'ทุกคนถอย — ปล่อยให้เครื่องวิเคราะห์', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'เครื่องสั่งให้ช็อกหรือไม่?',
        yesNextId: 's5', noNextId: 's6' },
      { id: 's5', kind: 'action', tone: 'danger', text: 'ตะโกน "ทุกคนถอย" → กดปุ่มช็อก', nextId: 's6' },
      { id: 's6', kind: 'action', text: 'ทำ CPR ต่อ 2 นาที — เครื่องจะวิเคราะห์ซ้ำเอง', terminal: true },
    ],
  },
  {
    id: 'choking',
    title: 'สำลัก (Choking)',
    icon: 'AlertCircle',
    color: '#D97706',
    summary: 'อุดกั้นทางเดินหายใจจากสิ่งแปลกปลอม',
    steps: [
      { id: 's1', kind: 'check', text: 'ผู้ป่วยไอออกได้ดีหรือพูดได้หรือไม่?',
        yesNextId: 'cough', noNextId: 's2' },
      { id: 'cough', kind: 'action', text: 'ให้กำลังใจให้ไอต่อ — เฝ้าใกล้ ๆ ห้ามตบหลัง', terminal: true },
      { id: 's2', kind: 'check', text: 'ผู้ป่วยอายุ 1 ปีขึ้นไปหรือไม่?',
        yesNextId: 's3', noNextId: 'infant' },
      { id: 'infant', kind: 'action', tone: 'warning',
        text: 'เด็กเล็ก: นอนคว่ำบนแขน ตบหลัง 5 ครั้ง สลับนอนหงายกดอก 5 ครั้ง', terminal: true },
      { id: 's3', kind: 'action', text: 'ตบกลางหลัง 5 ครั้ง', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'หลุดออกหรือยัง?',
        yesNextId: 'done', noNextId: 's5' },
      { id: 's5', kind: 'action', text: 'รัดท้อง (Heimlich) 5 ครั้ง', nextId: 's6' },
      { id: 's6', kind: 'check', text: 'ผู้ป่วยหมดสติหรือไม่?',
        yesNextId: 'cpr', noNextId: 's3' },
      { id: 'cpr', kind: 'goto', text: 'โทร 1669 และเริ่ม CPR', targetId: 'cpr', terminal: true },
      { id: 'done', kind: 'action', text: 'เฝ้าสังเกต ถ้ามีอาการผิดปกติพาไป รพ.', terminal: true },
    ],
  },
  {
    id: 'bleeding',
    title: 'ห้ามเลือด',
    icon: 'Droplet',
    color: '#DC2626',
    summary: 'จัดการบาดแผลและเลือดออก',
    steps: [
      { id: 's1', kind: 'action', text: 'ใส่ถุงมือ/ถุงพลาสติกป้องกันตัวเอง', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'กดแผลตรง ๆ ด้วยผ้าสะอาด', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'ยกอวัยวะให้สูงกว่าหัวใจ ถ้าทำได้', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'เลือดหยุดภายใน 10 นาทีหรือไม่?',
        yesNextId: 'done', noNextId: 'call' },
      { id: 'call', kind: 'call', tone: 'danger', text: 'โทร 1669 — กดต่อจนรถพยาบาลถึง', terminal: true },
      { id: 'done', kind: 'action', text: 'พันแผลให้แน่นพอ — เฝ้าสังเกตอาการ', terminal: true },
    ],
  },
  {
    id: 'burns',
    title: 'แผลไหม้',
    icon: 'Flame',
    color: '#EA580C',
    summary: 'น้ำร้อนลวก ไฟไหม้ เคมี',
    steps: [
      { id: 's1', kind: 'action', text: 'ย้ายผู้ป่วยออกจากแหล่งความร้อน', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'ราดน้ำสะอาดอุณหภูมิห้องไหลผ่าน 15–20 นาที', nextId: 's3' },
      { id: 's3', kind: 'action', tone: 'danger',
        text: 'อย่าใส่ยาสีฟัน น้ำปลา ครีม น้ำมัน หรือน้ำแข็งโดยตรง', nextId: 's4' },
      { id: 's4', kind: 'check',
        text: 'แผลใหญ่กว่าฝ่ามือ / ไหม้ที่ใบหน้า มือ เท้า อวัยวะเพศ / มีตุ่มพอง?',
        yesNextId: 'call', noNextId: 'done' },
      { id: 'call', kind: 'call', tone: 'danger', text: 'พาไป รพ. หรือโทร 1669', terminal: true },
      { id: 'done', kind: 'action', text: 'พันด้วยผ้าสะอาด — สังเกตอาการ 24 ชม.', terminal: true },
    ],
  },
  {
    id: 'fracture',
    title: 'กระดูกหัก',
    icon: 'Bone',
    color: '#7C3AED',
    summary: 'ดามและจัดท่าก่อนนำส่ง',
    steps: [
      { id: 's1', kind: 'action', tone: 'warning', text: 'ห้ามดึงให้กระดูกเข้าที่', nextId: 's2' },
      { id: 's2', kind: 'check', text: 'มีกระดูกโผล่ออกมาจากผิวหนัง?',
        yesNextId: 'open', noNextId: 's3' },
      { id: 'open', kind: 'action', tone: 'danger',
        text: 'ปิดแผลด้วยผ้าสะอาด ห้ามดันกลับ → โทร 1669', terminal: true },
      { id: 's3', kind: 'action', text: 'ดามด้วยอุปกรณ์แข็ง (กระดาน หนังสือพิมพ์ม้วน) ยาวคร่อมข้อทั้งสองข้าง', nextId: 's4' },
      { id: 's4', kind: 'action', text: 'พันด้วยผ้าให้แน่น แต่ไม่รัดจนเลือดไม่เดิน', nextId: 's5' },
      { id: 's5', kind: 'action', text: 'นำส่ง รพ.', terminal: true },
    ],
  },
  {
    id: 'fainting',
    title: 'เป็นลม/หมดสติชั่วคราว',
    icon: 'User',
    color: '#0EA5E9',
    summary: 'จัดท่านอนและประเมินอาการ',
    steps: [
      { id: 's1', kind: 'action', text: 'จัดให้นอนหงาย ยกขาสูง 30 ซม.', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'คลายเสื้อผ้าที่รัดคอ/เอว', nextId: 's3' },
      { id: 's3', kind: 'check', text: 'รู้สึกตัวภายใน 1 นาทีหรือไม่?',
        yesNextId: 'wake', noNextId: 'call' },
      { id: 'wake', kind: 'action', text: 'ให้นอนพักต่อ 5–10 นาที — ดื่มน้ำหวานเล็กน้อย', terminal: true },
      { id: 'call', kind: 'goto', text: 'โทร 1669 และเริ่มประเมินตาม flowchart CPR', targetId: 'cpr', terminal: true },
    ],
  },
  {
    id: 'seizure',
    title: 'ชัก',
    icon: 'Activity',
    color: '#7C3AED',
    summary: 'ระหว่างชักและหลังชัก',
    steps: [
      { id: 's1', kind: 'action', text: 'เคลียร์ของแข็งรอบตัว รองหัวด้วยของนุ่ม', nextId: 's2' },
      { id: 's2', kind: 'action', tone: 'danger', text: 'ห้ามใส่อะไรในปาก ห้ามจับกดให้หยุดดิ้น', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'จับเวลาว่าชักนานเท่าไร', nextId: 's4' },
      { id: 's4', kind: 'check', text: 'ชักนานเกิน 5 นาที หรือชักซ้ำ?',
        yesNextId: 'call', noNextId: 's5' },
      { id: 'call', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที', terminal: true },
      { id: 's5', kind: 'action', text: 'เมื่อหยุดชัก จัดท่าตะแคง (Recovery position)', terminal: true },
    ],
  },
  {
    id: 'drowning',
    title: 'จมน้ำ',
    icon: 'Wind',
    color: '#0EA5E9',
    summary: 'การช่วยเหลือผู้จมน้ำ',
    steps: [
      { id: 's1', kind: 'action', tone: 'warning',
        text: 'อย่ากระโดดลงไป — ใช้หลัก "ตะโกน-โยน-ยื่น"', nextId: 's2' },
      { id: 's2', kind: 'action', text: 'ตะโกนเรียกความช่วยเหลือ + โยนวัตถุลอย + ยื่นไม้/ผ้า', nextId: 's3' },
      { id: 's3', kind: 'check', text: 'นำขึ้นมาแล้ว — หายใจหรือไม่?',
        yesNextId: 'recovery', noNextId: 'cpr' },
      { id: 'recovery', kind: 'action', text: 'จัดท่าตะแคง รักษาความอบอุ่น พาไป รพ.', terminal: true },
      { id: 'cpr', kind: 'goto', text: 'เริ่ม CPR ทันที — ห้ามล้วงน้ำออก', targetId: 'cpr', terminal: true },
    ],
  },
  {
    id: 'snake-bite',
    title: 'งูกัด',
    icon: 'Shield',
    color: '#15803D',
    summary: 'การปฐมพยาบาลผู้ถูกงูกัด',
    steps: [
      { id: 's1', kind: 'action', text: 'ให้ผู้ป่วยอยู่นิ่ง ๆ ระดับแผลต่ำกว่าหัวใจ', nextId: 's2' },
      { id: 's2', kind: 'action', tone: 'danger',
        text: 'ห้ามดูดพิษ ห้ามรัด ห้ามกรีดแผล ห้ามประคบน้ำแข็ง', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'ถอดแหวน/นาฬิกาออก เพราะอาจบวม', nextId: 's4' },
      { id: 's4', kind: 'action', text: 'จดจำลักษณะงู (สี ลาย) ถ้าทำได้ — ไม่ต้องไล่จับ', nextId: 's5' },
      { id: 's5', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที — นำส่ง รพ. เร็วที่สุด', terminal: true },
    ],
  },
  {
    id: 'heat-stroke',
    title: 'ลมแดด',
    icon: 'Sun',
    color: '#D97706',
    summary: 'Heat Stroke — ภาวะฉุกเฉิน',
    steps: [
      { id: 's1', kind: 'check',
        text: 'ตัวร้อน (>40°C) ผิวแดงแห้ง สับสน หรือหมดสติ?',
        yesNextId: 's2', noNextId: 'mild' },
      { id: 'mild', kind: 'action',
        text: 'อาจเป็นเพลียแดด — ย้ายเข้าที่ร่ม ดื่มน้ำเกลือแร่ พัก 30 นาที', terminal: true },
      { id: 's2', kind: 'call', tone: 'danger', text: 'โทร 1669 ทันที', nextId: 's3' },
      { id: 's3', kind: 'action', text: 'ย้ายเข้าที่ร่มเย็น คลายเสื้อ', nextId: 's4' },
      { id: 's4', kind: 'action',
        text: 'ใช้น้ำเย็นราดตัว/น้ำแข็งห่อผ้าประคบรักแร้-ขาหนีบ-คอ', nextId: 's5' },
      { id: 's5', kind: 'action', text: 'พัดให้ระเหย — เฝ้าจนรถพยาบาลถึง', terminal: true },
    ],
  },
]

export const algorithmsById = Object.fromEntries(algorithms.map(a => [a.id, a]))
